### ISSUE TITLE
Consider using `ascii-string` for names and namespaces

### ISSUE THREAD

**Issue by lgalabru** [Trust-Machines/BNS-V2#57]
In `bns-v1` we ended up using buffers as a data type for working with names and namespaces.
Clarity 2.1 introduced a few convenient functions `from-consensus-buff` / `to-consensus-buff` that would help us using the `ascii-string` type instead - which would make the usage of bns more convenient, out of the box - names / namespaces would become readable out of the box.

**Comment by larrysalibra** [comment]
+1 to using `ascii-string` instead of buffers for names and namespaces. buffers have cause a lot of developer trouble over the years making it harder for people to debug code

**Comment by Patotking12** [comment]
I do not think that for this version we can do that. Thanks for the feedback!
