### ISSUE TITLE
Implement readonly function to get name price

### ISSUE THREAD

**Issue by MicaiahReid** [Trust-Machines/BNS-V2#64]
@lgalabru  and I are the process of testing the BNS-V2 contract using txtx.

We're creating some runbooks that will make it easy for users to try out the protocol.

When preordering + registering a BNS name, I noticed that the expected `stx-to-burn` is calculated by the private function `compute-name-price`. There's currently no way (as far as I can tell) for a user to determine what the required `stx-to-burn` is for a given name.

Is there a plan to introduce a read only wrapper around `comput-name-price` (a la BNS v1's `get-name-price` function)? It seems like the contract would be unusable without this function, but maybe I'm missing something?

**Comment by Patotking12** [comment]
If we know the namespace, we know the pricing function, and we know the formula being used, this should be calculated by the front end providing the registration process, but yes we can implement a read only function to get a name price

**Comment by Patotking12** [comment]
That for managed namespaces the returned information won't be the real one since managers will handle their own pricing function, but I can add a check for that. 

Will work on adding it back

**Comment by Patotking12** [comment]
Thanks for this @lgalabru @MicaiahReid

**Comment by Patotking12** [comment]
@lgalabru @MicaiahReid this issue has been addressed and merged
