### ISSUE TITLE
name-claim-fast doesn’t appear to respect preorders

### ISSUE THREAD

**Issue by larrysalibra** [Trust-Machines/BNS-V2#65]
It looks like that if user A preorders a name using [`name-preorder`](https://github.com/Trust-Machines/BNS-V2/blob/061b23a9440c61463cd063323591415db40833a4/contracts/BNS-V2.clar#L973), the preorder confirms and then in the next block, user B uses [`name-claim-fast`](https://github.com/Trust-Machines/BNS-V2/blob/061b23a9440c61463cd063323591415db40833a4/contracts/BNS-V2.clar#L889C17-L889C32) to register the same name, that user B will get the name.

I would expect that `name-claim-fast` will only succeed if there are no valid preorders within  the [`PREORDER-CLAIMABILITY-TTL`](https://github.com/Trust-Machines/BNS-V2/blob/061b23a9440c61463cd063323591415db40833a4/contracts/BNS-V2.clar#L17) time to live window.

Please correct me if I'm wrong on this!

**Comment by Patotking12** [comment]
The issue here is that when name-claim-fast is executed there is no way of knowing if a preorder was ever made for that name. 

But if you look closely into the name-register function this "problem" is resolved giving the name to the correct owner, in this case the user that preordered the name first

**Comment by Patotking12** [comment]
Exactly. Scenarios:
1. Alice preorders a name - A block later Bob preorders a name - Bob registers the name and gets the name - Alice before the TTL has passed on her preorder, registers the name, the name gets transferred from Bob to Alice (the rightful owner)
2. Alice preorders a name - A block later Bob fast-claims a name - Alice before the TTL has passed on her preorder, registers the name, the name gets transferred from Bob to Alice (the rightful owner)

**Comment by Patotking12** [comment]
Closing this issue since everything has been clarified
