### ISSUE TITLE
Repo is missing a license

### ISSUE THREAD

**Issue by larrysalibra** [Trust-Machines/BNS-V2#66]
What's the license of this code? 

I'd suggested MIT like Bitcoin or GPL-3.0 like Stacks.

**Comment by Patotking12** [comment]
Ok will talk with the team to update this

**Comment by Patotking12** [comment]
We will proceed with the MIT license

**Comment by Patotking12** [comment]
License Added

**Comment by larrysalibra** [comment]
Great! Thank you!
