### ISSUE TITLE
name-claim-fast can be used to snipe

### ISSUE THREAD

**Issue by dartman10** [Trust-Machines/BNS-V2#82]
It seems the function `name-claim-fast` can be used for sniping. Once a `name-register` transaction appears, an actor can initiate a `name-claim-fast` transaction upon seeing the non-hashed fqn.

**Comment by Patotking12** [comment]
Hey! @dartman10, name-register can not be snipped.

We do a check on name-register to see if the preorder happened before the name-claim-fast, that way even though the name-claim-fast happens and mints the name, as soon as the name-register happens it will transfer the name to the correct owner who preorder it first
